version: '3'
services:

  api:
    build: ./api/
    ports:
      #CherryPy webserver port mapping
      - "9091:8080"
      #Python remote debug port mapping
      - "10091:8081"

    volumes:
      - ./api/:/app/src/
